### PR TITLE
Update LICENSE - Fix spacing (Release Audit)

### PR DESCRIPTION
**Pull request by manez**
# What does this Pull Request do?

Centers the header on the license, to match most of the others. Very trivial.
# How should this be tested?

Go to the license. Is the first line centered? We're good 😄

### CODE REVIEW

**Comment by DiegoPino** [comment]
@manez not sure what is failing here: the Travis error related to this one usually happens when you merge something during a travis run, which is clearly not the case. I restarted the failed job without luck.
Will ping here @dannylamb as release manager, but, if possible will also ask @ruebot for help since he has more experience than any other i know on travis. 😱 

Particular error: 
`The command "eval git fetch origin +refs/pull/41/merge:" failed. Retrying, 2 of 3.`
which should happen if pull 41 was merged. (which was merged) but this one is 40!

UPDATE: as @whikloj correctly just stated: 41 is failing (because it was merged during a run). Travis is not separating different branches somehow, so since 41 never could pass, this one, that does pass, fails..

**Comment by dannylamb** [comment]
Will closing this PR and making a new one address this?

**Comment by whikloj** [comment]
I think so, but I'm not 100%

**Comment by DiegoPino** [comment]
@dannylamb is that (which needs @manez intervention) or: we reopen/revert #41. Wait for travis to run there, merge and then merge this

**Comment by dannylamb** [comment]
just make a new PR? ¯_(ツ)_/¯

seems easier.

**Comment by DiegoPino** [comment]
@dannylamb ok, but i still feel it's not a good idea to merge without letting travis pass( #41 ) even when we are sure it's Travis fault, for the record.
@manez could you please close this one, and pull again, from a different local branch again?

**Comment by dannylamb** [comment]
@DiegoPino if new PR doesn't pass, we won't merge it.

**Pull request closed without merging**
